sudo: false
dist: trusty
language: python
python:
  - "2.7"
install:
  - nvm install 4.2.6
  - nvm use 4.2.4
  - npm install -g bower gulp
  - node -v
  - cd angular_app
  - npm install
  - cd ..
  - ./install.sh
  # - nvm install 4.2
  # - npm install -g bower gulp
  # - cd angular_app
  # - npm install
script:
  - flask/bin/nosetests
  # - cd angular_app && npm test
deploy:
  provider: heroku
  app: cedar14-githubanalytics
  api_key:
    - secure: **something special**
