sudo: false
dist: trusty
language: python
python:
  - "2.7"
node_js:
  - "4.2.6"
install:
  - ./install.sh
before_script:
  - "npm install -g bower gulp"
  - "cd angular_app"
  - "npm install"
  - "cd .."
script:
  - flask/bin/nosetests
