sudo: false
dist: trusty
language: python
python:
  - "2.7"
install:
  - ./install.sh
  # - nvm install 4.2
  # - npm install -g bower gulp npm@2.14.12
  # - cd angular_app
  # - npm install
script:
  - flask/bin/nosetests
  # - cd angular_app && npm test

